// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvbvfsjqmlmlqyuhswpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2YnZmc2pxbWxtbHF5dWhzd3B2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2OTY4NTEsImV4cCI6MjA2MjI3Mjg1MX0.FMAL8i_qFf1J0G3ffmN7IkBe8Fi6RVYc57FCc5uEZaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);